runtime: nodejs
service: default
env: flex

network:
  instance_tag: webapp

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.75

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
